### ISSUE TITLE
Include GD in PHP binary

### ISSUE THREAD

**Issue by benmerckx** [DFabric/apps-static#1]
Any chance to include the GD library in the PHP binary (`--with-gd`)? I've tried this a couple times now, but keep hitting various compile errors during the configure step which I can't figure out.

**Comment by j8r** [comment]
The `.a` archives was missing for `freetype`. I've added `freetype-static` and other freetype dependencies - PHP 7.2.12 compiles!
We still need to do `export DTAG=edge` before `build-static` because `sqlite-static` is only present on Alpine Edge.

**Comment by j8r** [comment]
Thanks @benmerckx , the compiled binaries are available.
