### ISSUE TITLE
cant compile php 7.3.7 x86

### ISSUE THREAD

**Issue by donaldsteele** [DFabric/apps-static#3]
when trying to build the x86 version of php 7.3.7 the file  https://dl.bintray.com/dfabric/apps-static/curl-static_7.64.1_linux_x86-64.tar.xz is downloaded and installed which is for 64bit os's , please compile for 86 and add to the repo for the SHA512SUMS file

the work around is to compile curl static locally and inject into the docker image before you manually kick off main.sh (in dev mode).

**Comment by j8r** [comment]
I understand the problem, I would like to be fixed upstream on Alpine but that's not that easy.
I think I figured out [how to do](https://github.com/alpinelinux/aports/pull/6264#issuecomment-490007696), and will work on it and test it when I will have the time.
